spring:
  application:
    name: restaurant-voting
  jpa:
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:mem:voting
#        tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    username: sa
    password:
  jackson:
    visibility.field: any
    visibility.getter: none
    visibility.setter: none
    visibility.is-getter: none
    default-property-inclusion: non_empty
  cache:
    cache-names: users
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s

logging:
  level:
    root: WARN
    ru.erulaev.restaurantvoting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

springdoc.swagger-ui.path: /