spring:
  application:
    name: restaurant-voting
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:mem:voting
#        tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    username: sa
    password:
  jackson:
    visibility.field: any
    visibility.getter: none
    visibility.setter: none
    visibility.is-getter: none
    default-property-inclusion: non_empty
logging:
  level:
    root: WARN
    ru.erulaev.restaurantvoting: DEBUG